import type { Box, Container, PackingResult, Pallet, PlacedItem, Dimensions, ContainerLoad } from './types';
// Stuffing Algorithm v0.1.1
// Post-processing pipeline fixed
// Top-Up & Full Mix behavior stabilized
// import { v4 as uuidv4 } from 'uuid';
import { packGridCore, type GridVolume } from './packGridCore';
import {
    PALLET_BASE_HEIGHT_MM,
    MIN_USABLE_STRIP_WIDTH_MM,
    LAYER_GROUPING_TOLERANCE_MM,
    PALLET_POSITION_TOLERANCE_MM,
    DEFAULT_MARGIN_MM,
    MAX_PALLET_STACK_HEIGHT,
    GROUND_SHELF_TOLERANCE_MM
} from './constants';
import { deepClone, parseLayerConfig } from './utils';
import { selectBestOrientation } from './orientationSelector';
import { runPostProcessingPipeline } from './postProcessingPipeline';
import { debugLogger } from './debugLogger';

console.log(">>> PACKING ALGO FILE LOADED: v0.1.1 <<<");
console.log("Path: packages/core/src/packingAlgorithm.ts");

/**
 * AXIS LAW (IMMUTABLE):
 * packGridCore OUTPUTS positions in its internal coordinate system:
 *   p[0] = X = Width coordinate
 *   p[1] = Y = Length coordinate  
 *   p[2] = Z = Height coordinate
 *
 * PlacedItem EXPECTS positions in container coordinates:
 *   position[0] = Length
 *   position[1] = Height
 *   position[2] = Width
 *
 * Therefore we must remap: [Width, Length, Height] -> [Length, Height, Width]
 */
function kernelToPlacedPosition(p: [number, number, number]): [number, number, number] {
    return [p[1], p[2], p[0]]; // [Length, Height, Width] from [Width, Length, Height]
}


interface PackingScenarioResult {
    loads: ContainerLoad[];
    totalItems: number;
    totalContainers: number;
    unpackedItems: number;
    packedBoxDimensions?: Dimensions;
    errors: string[];
    actualUsedVolume?: number;
}

/**
 * IMPORTANT:
 * All placement coordinates MUST be generated by packGridCore.
 * No other function in this file may compute or mutate X/Y/Z positions.
 */

/**
 * ARCHITECTURAL FIX: SURFACE DETECTION SYSTEM (Change to see if git works)
 * Adjusted to find horizontal ground space
 */
interface Shelf {
    startX: number;
    endX: number;
    y: number; // The height of this shelf
    z?: number; // Start Z position (for side strips)
    width: number; // Available Z-width
    type: 'gap' | 'peak' | 'ground_horizontal' | 'side_strip';
}

const findAvailableShelves = (
    load: ContainerLoad,
    containerDims: Dimensions,
    margins: { length?: number; width?: number; height?: number }
): Shelf[] => {
    const marginL = margins.length ?? DEFAULT_MARGIN_MM;
    const marginH = margins.height ?? DEFAULT_MARGIN_MM;
    const marginW = margins.width ?? DEFAULT_MARGIN_MM;

    // Flatten items into a simplified 2D profile (X vs MaxY)
    const sortedItems = [...load.items].sort((a, b) => a.position[0] - b.position[0]);

    // If empty, whole floor is available
    if (sortedItems.length === 0) {
        return [{
            startX: marginL,
            endX: containerDims.length - marginL,
            y: marginH,
            width: containerDims.width - marginW * 2,
            type: 'ground_horizontal'
        }];
    }

    // Detect Global Max X (Rightmost edge of the load)
    let absoluteMaxX = 0;

    // Group items by their approximate top Y (tolerance 5mm) to find vertical shelves
    // Store a LIST of supported segments for each height, to handle gaps
    const layers = new Map<number, { minX: number, maxX: number, minZ: number, maxZ: number }[]>();

    sortedItems.forEach(item => {
        const top = item.position[1] + item.dimensions.height / 2;
        const right = item.position[0] + item.dimensions.length / 2;

        if (right > absoluteMaxX) absoluteMaxX = right;

        // Round to nearest 10mm to group effectively
        const roundedTop = Math.round(top / LAYER_GROUPING_TOLERANCE_MM) * LAYER_GROUPING_TOLERANCE_MM;

        const itemMinX = item.position[0] - item.dimensions.length / 2;
        const itemMaxX = item.position[0] + item.dimensions.length / 2;
        const itemMinZ = item.position[2] - item.dimensions.width / 2;
        const itemMaxZ = item.position[2] + item.dimensions.width / 2;

        if (!layers.has(roundedTop)) {
            layers.set(roundedTop, [{ minX: itemMinX, maxX: itemMaxX, minZ: itemMinZ, maxZ: itemMaxZ }]);
        } else {
            const segments = layers.get(roundedTop)!;
            let merged = false;

            // Try to merge with existing segments if they overlap or touch
            for (const segment of segments) {
                // Check for overlap/touch in X and Z
                const xOverlap = (itemMinX <= segment.maxX + 1) && (itemMaxX >= segment.minX - 1);
                const zOverlap = (itemMinZ <= segment.maxZ + 1) && (itemMaxZ >= segment.minZ - 1);

                if (xOverlap && zOverlap) {
                    segment.minX = Math.min(segment.minX, itemMinX);
                    segment.maxX = Math.max(segment.maxX, itemMaxX);
                    segment.minZ = Math.min(segment.minZ, itemMinZ);
                    segment.maxZ = Math.max(segment.maxZ, itemMaxZ);
                    merged = true;
                    break;
                }
            }

            if (!merged) {
                segments.push({ minX: itemMinX, maxX: itemMaxX, minZ: itemMinZ, maxZ: itemMaxZ });
            }
        }
    });

    const shelves: Shelf[] = [];

    // 1. Horizontal Ground Shelf (The space AFTER the last item)
    if (absoluteMaxX < containerDims.length - marginL - GROUND_SHELF_TOLERANCE_MM) {
        shelves.push({
            startX: absoluteMaxX,
            endX: containerDims.length - marginL,
            y: marginH, // Start at ground (plus margin)
            width: containerDims.width - marginW * 2,
            type: 'ground_horizontal'
        });
    }

    // 1b. Internal Ground Gaps (Space BEFORE the last item)
    // Scan for significant gaps between items on the ground level
    if (sortedItems.length > 0) {
        // Sort by minX
        const xSorted = [...sortedItems].sort((a, b) => (a.position[0] - a.dimensions.length / 2) - (b.position[0] - b.dimensions.length / 2));

        let currentX = marginL;
        for (const item of xSorted) {
            const itemLeft = item.position[0] - item.dimensions.length / 2;
            const itemRight = item.position[0] + item.dimensions.length / 2;

            // Check if there is a gap before this item
            if (itemLeft > currentX + GROUND_SHELF_TOLERANCE_MM) {
                // Found a gap!
                shelves.push({
                    startX: currentX,
                    endX: itemLeft,
                    y: marginH,
                    width: containerDims.width - marginW * 2,
                    type: 'ground_horizontal' // Treat as ground shelf
                });
            }

            // Advance currentX if this item extends further
            if (itemRight > currentX) {
                currentX = itemRight;
            }
        }
    }

    // 2. Vertical Shelves (Peak & Gaps)
    // const sortedLayers = Array.from(layers.entries()).sort((a, b) => b[0] - a[0]); // Descending Height

    // 3. Side Strip Detection (Z-axis gap)
    // Find the maximum Z used by any item in the load
    let maxZ = 0;
    load.items.forEach(item => {
        const front = item.position[2] + item.dimensions.width / 2;
        if (front > maxZ) maxZ = front;
    });

    if (load.items.length === 0) maxZ = marginW;

    const remainingWidth = containerDims.width - marginW - maxZ;
    const minUsableWidth = MIN_USABLE_STRIP_WIDTH_MM;

    if (remainingWidth > minUsableWidth) {
        shelves.push({
            startX: marginL,
            endX: containerDims.length - marginL,
            y: marginH,
            z: maxZ, // Start after the existing load
            width: remainingWidth,
            type: 'side_strip'
        });
    }


    return shelves;
};


// Helper to pack a single material into a container (or remaining space)
const packMaterial = (
    boxInput: Box,
    container: Container,
    pallet: Pallet,
    quantity: number,
    layerConfig: string,
    materialId: number,
    startOffset: number = 0, // Offset in Length (x-axis)
    existingLoad: ContainerLoad | null = null, // If appending to an existing load
    margins: { length?: number; width?: number; height?: number } = { length: 20, width: 20, height: 20 },
    baseY: number = 0, // Starting Y position (for stacking on top of other materials)
    baseZ: number = 0, // Starting Z position (for side strips)
    allowNewContainers: boolean = true, // Whether to create new containers if overflow
    maxLen?: number // Optional: Maximum length available for this packing operation
): PackingScenarioResult => {
    // 1. Enforce State Immutability (Deep Clone)
    const box = deepClone(boxInput);
    // 1. Validate inputs
    if (
        box.dimensions.length <= 0 || box.dimensions.width <= 0 || box.dimensions.height <= 0 ||
        container.dimensions.length <= 0 || container.dimensions.width <= 0 || container.dimensions.height <= 0 ||
        (pallet.usePallet && (pallet.dimensions.length <= 0 || pallet.dimensions.width <= 0 || pallet.maxLoadHeight <= 0))
    ) {
        return {
            loads: [],
            totalItems: 0,
            totalContainers: 0,
            unpackedItems: quantity,
            errors: []
        };
    }

    const marginL = margins.length ?? DEFAULT_MARGIN_MM;
    const marginW = margins.width ?? DEFAULT_MARGIN_MM;
    const marginH = margins.height ?? DEFAULT_MARGIN_MM;

    const contW = container.dimensions.width - marginW * 2 - baseZ;
    const contH = container.dimensions.height - marginH * 2 - baseY;

    let effectiveContainerLength = (container.dimensions.length - marginL * 2) - startOffset;
    if (maxLen !== undefined) {
        effectiveContainerLength = Math.min(effectiveContainerLength, maxLen);
    }

    if (effectiveContainerLength <= 0) {
        return {
            loads: [],
            totalItems: 0,
            totalContainers: 0,
            unpackedItems: quantity,
            errors: []
        };
    }

    // 2. Determine the unit to pack (Box or Loaded Pallet)
    let bestResult: PackingScenarioResult | null = null;
    const errors: string[] = [];

    // Generate all 6 permutations
    const allPermutations: Dimensions[] = [
        { length: box.dimensions.length, width: box.dimensions.width, height: box.dimensions.height },
        { length: box.dimensions.length, width: box.dimensions.height, height: box.dimensions.width },
        { length: box.dimensions.width, width: box.dimensions.length, height: box.dimensions.height },
        { length: box.dimensions.width, width: box.dimensions.height, height: box.dimensions.length },
        { length: box.dimensions.height, width: box.dimensions.length, height: box.dimensions.width },
        { length: box.dimensions.height, width: box.dimensions.width, height: box.dimensions.length }
    ];

    // Filter by Allowed Rotations
    // Filter by Allowed Rotations
    const allowedOrientations: Dimensions[] = [];
    // Strict Mode: Only allow explicit rotations.
    // If all are false, rotationCount is 0, array remains empty, Fallback adds default.

    // y (Horizontal): Height = Original Height (indices 0, 2)
    if (box.allowedRotations.y) {
        allowedOrientations.push(allPermutations[0]);
        allowedOrientations.push(allPermutations[2]);
    }
    // x (Vertical): Height = Original Length (indices 3, 5)
    if (box.allowedRotations.x) {
        allowedOrientations.push(allPermutations[3]);
        allowedOrientations.push(allPermutations[5]);
    }
    // z (Flat): Height = Original Width (indices 1, 4)
    if (box.allowedRotations.z) {
        allowedOrientations.push(allPermutations[1]);
        allowedOrientations.push(allPermutations[4]);
    }

    // Fallback if empty (shouldn't happen if logic is correct, but safe)
    if (allowedOrientations.length === 0) {
        allowedOrientations.push(allPermutations[0]);
    }

    // ORIENTATION SELECTION
    // Determine the target container for optimization
    let selectionTarget: Container;

    if (pallet.usePallet) {
        // Optimize for the Pallet (Acting as a mini-container)
        selectionTarget = {
            name: 'Pallet Proxy',
            type: 'custom',
            dimensions: {
                length: pallet.dimensions.length,
                width: pallet.dimensions.width,
                height: pallet.maxLoadHeight // Use max load height? Or just arbitrary for footprint?
                // packGridCore uses Height for volume calculation and fill order.
                // Pallet pack is mostly 2D (Floor limits), but height matters for quantity.
            },
        };

    } else {
        // Optimize for the actual Container
        // Ensure we pass the dimensions relevant to packing (inside margins)?
        // selectBestOrientation uses container dims for 'volume' and 'bounds'.
        // If we want to be precise, we should pass the dimensions *after* margins.
        // selectBestOrientation expects a Container object, so we create a proxy.

        selectionTarget = {
            ...container,
            dimensions: {
                length: effectiveContainerLength,
                width: contW,
                height: contH
            }
        };
    }

    const chosenDimensions = selectBestOrientation(selectionTarget, box, allowedOrientations);

    // --------------------------------------------------------------------------
    // SINGLE PASS PACKING (Immutable Orientation)
    // --------------------------------------------------------------------------

    // Use the chosen dimensions implicitly
    const currentBoxDims = chosenDimensions;
    let unitDimensions: Dimensions;
    let unitType: 'box' | 'pallet';
    let itemsPerUnit = 1;

    if (pallet.usePallet) {
        unitType = 'pallet';
        let cols: number;
        let rows: number;
        let layers: number;
        const parsedConfig = parseLayerConfig(layerConfig);

        if (parsedConfig) {
            const { horizontal, vertical } = parsedConfig;
            const maxPhysicalItemsPerLayer = Math.floor(pallet.dimensions.length / currentBoxDims.length) * Math.floor(pallet.dimensions.width / currentBoxDims.width);
            if (horizontal > maxPhysicalItemsPerLayer) {
                errors.push(`Mat ${materialId}: Layer config items (${horizontal}) exceeds physical limit (${maxPhysicalItemsPerLayer}). Clamped.`);
                cols = maxPhysicalItemsPerLayer;
            } else {
                cols = horizontal;
            }
            rows = 1;
            const palletBaseHeight = PALLET_BASE_HEIGHT_MM;
            const availableHeight = pallet.maxLoadHeight - palletBaseHeight;
            const maxPossibleLayers = Math.floor(availableHeight / currentBoxDims.height);
            if (vertical > maxPossibleLayers) {
                layers = maxPossibleLayers;
            } else {
                layers = vertical;
            }
        } else {
            cols = Math.floor(pallet.dimensions.length / currentBoxDims.length);
            rows = Math.floor(pallet.dimensions.width / currentBoxDims.width);
            const palletBaseHeight = PALLET_BASE_HEIGHT_MM;
            const availableHeight = pallet.maxLoadHeight - palletBaseHeight;
            layers = Math.floor(availableHeight / currentBoxDims.height);
        }

        const palletBaseHeight = PALLET_BASE_HEIGHT_MM;
        const actualUnitHeight = palletBaseHeight + (layers * currentBoxDims.height);
        const effectiveUnitHeight = actualUnitHeight;

        if (cols > 0 && rows > 0 && layers > 0) {
            itemsPerUnit = cols * rows * layers;
            unitDimensions = {
                length: pallet.dimensions.length,
                width: pallet.dimensions.width,
                height: effectiveUnitHeight
            };
        } else {
            // Fallback if pallet doesn't fit even one item?
            // Return empty result
            return {
                loads: [],
                totalItems: 0,
                totalContainers: 0,
                unpackedItems: quantity,
                errors: [...errors, 'Pallet configuration invalid or does not fit any items.']
            };
        }

    } else {
        unitType = 'box';
        const parsedConfig = parseLayerConfig(layerConfig);

        if (parsedConfig) {
            const { horizontal, vertical } = parsedConfig;
            const maxHorizontal = Math.floor(contW / currentBoxDims.width);
            const maxVertical = Math.floor(contH / currentBoxDims.height);

            let finalHorizontal = horizontal;
            let finalVertical = vertical;
            let clamped = false;

            if (horizontal > maxHorizontal) {
                finalHorizontal = maxHorizontal;
                clamped = true;
            }
            if (vertical > maxVertical) {
                finalVertical = maxVertical;
                clamped = true;
            }

            if (clamped) {
                errors.push(`Mat ${materialId}: Layer config ${horizontal}x${vertical} exceeds container. Clamped to ${finalHorizontal}x${finalVertical}.`);
            }
            finalHorizontal = Math.max(1, finalHorizontal);
            finalVertical = Math.max(1, finalVertical);

            const stackWidth = finalHorizontal * currentBoxDims.width;
            const stackHeight = finalVertical * currentBoxDims.height;
            unitDimensions = { length: currentBoxDims.length, width: stackWidth, height: stackHeight };
            itemsPerUnit = finalHorizontal * finalVertical;
        } else {
            unitDimensions = currentBoxDims;
            itemsPerUnit = 1;
        }
    }

    // 3. Calculate grid using Kernel
    const effectiveLength = effectiveContainerLength;
    const effectiveWidth = contW;
    let effectiveHeight = contH;

    if (pallet.usePallet) {
        if (pallet.stackPallets) {
            effectiveHeight = Math.min(contH, MAX_PALLET_STACK_HEIGHT * unitDimensions.height);
        } else {
            effectiveHeight = unitDimensions.height;
        }
    }
    if (!layerConfig && pallet.usePallet && pallet.stackPallets) {
        effectiveHeight = Math.min(contH, MAX_PALLET_STACK_HEIGHT * unitDimensions.height);
    }
    if (!pallet.usePallet && layerConfig && layerConfig.toLowerCase().includes('x')) {
        effectiveHeight = unitDimensions.height;
    }

    const volume: GridVolume = {
        origin: {
            x: marginW + baseZ,
            y: startOffset + marginL,
            z: marginH + baseY
        },
        bounds: {
            length: effectiveLength,
            width: effectiveWidth,
            height: effectiveHeight
        }
    };

    const gridPlacements = packGridCore(volume, unitDimensions);

    if (gridPlacements.length > 0) {
        const totalUnitsNeeded = Math.ceil(quantity / itemsPerUnit);
        const loads: ContainerLoad[] = [];
        let remainingUnits = totalUnitsNeeded;
        let remainingItemsTotal = quantity;
        let loadId = existingLoad ? existingLoad.id : 1;
        let totalItemsInScenario = 0;
        let totalActualUsedVolume = 0;

        // Handle Existing Load
        if (existingLoad) {
            const loadVolume: GridVolume = {
                origin: { x: marginW + baseZ, y: startOffset + marginL, z: marginH + baseY },
                bounds: { length: effectiveLength, width: effectiveWidth, height: effectiveHeight }
            };

            const gridPlacements = packGridCore(loadVolume, unitDimensions);
            const maxUnitsPerContainer = gridPlacements.length;
            const unitsInThisLoad = Math.min(remainingUnits, maxUnitsPerContainer);
            const placements: PlacedItem[] = [];
            let unitsPlaced = 0;

            for (const placement of gridPlacements) {
                if (unitsPlaced >= unitsInThisLoad) break;
                placements.push({
                    position: kernelToPlacedPosition(placement.position),
                    rotation: [0, 0, 0],
                    dimensions: placement.dimensions,
                    type: unitType,
                    itemCount: Math.min(itemsPerUnit, remainingItemsTotal),
                    materialId: materialId,
                    grid: {
                        cols: unitType === 'box' && layerConfig && layerConfig.includes('x') ? (itemsPerUnit > 1 ? Math.floor(unitDimensions.width / currentBoxDims.width) : 1) : (unitType === 'pallet' ? Math.floor(unitDimensions.width / currentBoxDims.width) : 1),
                        rows: unitType === 'pallet' ? Math.floor(unitDimensions.length / currentBoxDims.length) : 1,
                        layers: unitType === 'box' && layerConfig && layerConfig.includes('x') ? (itemsPerUnit > 1 ? Math.floor(unitDimensions.height / currentBoxDims.height) : 1) : (unitType === 'pallet' ? Math.floor((unitDimensions.height - PALLET_BASE_HEIGHT_MM) / currentBoxDims.height) : 1)
                    }
                });
                remainingItemsTotal -= Math.min(itemsPerUnit, remainingItemsTotal);
                unitsPlaced++;
                remainingUnits--;
            }

            const itemsInThisLoad = placements.reduce((sum, item) => sum + (item.itemCount || 0), 0);
            const totalItemsInLoad = existingLoad.itemCount + itemsInThisLoad;

            // Recalculate utilization
            const currentLoadVol = [...existingLoad.items, ...placements].reduce((sum, item) => sum + (item.dimensions.length * item.dimensions.width * item.dimensions.height), 0);
            const containerVol = container.dimensions.length * container.dimensions.width * container.dimensions.height;
            const newUtilization = (currentLoadVol / containerVol) * 100;

            loads.push({
                ...existingLoad,
                items: [...existingLoad.items, ...placements],
                itemCount: totalItemsInLoad,
                utilization: newUtilization
            });
            totalItemsInScenario += itemsInThisLoad;
            const boxVolume = box.dimensions.length * box.dimensions.width * box.dimensions.height;
            totalActualUsedVolume += itemsInThisLoad * boxVolume;
            loadId++;
        }

        // Handle New Containers
        while (allowNewContainers && remainingUnits > 0) {
            const fullContL = container.dimensions.length - marginL * 2;
            const fullContW = container.dimensions.width - marginW * 2;
            const fullContH = container.dimensions.height - marginH * 2;

            let fullEffectiveHeight = fullContH;
            if (pallet.usePallet) {
                if (pallet.stackPallets) {
                    fullEffectiveHeight = Math.min(fullContH, MAX_PALLET_STACK_HEIGHT * unitDimensions.height);
                } else {
                    fullEffectiveHeight = unitDimensions.height;
                }
            }
            if (!layerConfig && pallet.usePallet && pallet.stackPallets) {
                fullEffectiveHeight = Math.min(fullContH, MAX_PALLET_STACK_HEIGHT * unitDimensions.height);
            }
            if (!pallet.usePallet && layerConfig && layerConfig.toLowerCase().includes('x')) {
                fullEffectiveHeight = unitDimensions.height;
            }

            const loadVolume: GridVolume = {
                origin: { x: marginW, y: marginL, z: marginH },
                bounds: { length: fullContL, width: fullContW, height: fullEffectiveHeight }
            };

            const gridPlacements = packGridCore(loadVolume, unitDimensions);
            const fullMaxUnits = gridPlacements.length;
            const unitsInThisLoad = Math.min(remainingUnits, fullMaxUnits);
            const isFull = unitsInThisLoad === fullMaxUnits;
            const placements: PlacedItem[] = [];
            let unitsPlaced = 0;

            for (const placement of gridPlacements) {
                if (unitsPlaced >= unitsInThisLoad) break;
                placements.push({
                    position: kernelToPlacedPosition(placement.position),
                    rotation: [0, 0, 0],
                    dimensions: placement.dimensions,
                    type: unitType,
                    itemCount: Math.min(itemsPerUnit, remainingItemsTotal),
                    materialId: materialId,
                    grid: {
                        cols: unitType === 'box' && layerConfig && layerConfig.includes('x') ? (itemsPerUnit > 1 ? Math.floor(unitDimensions.width / currentBoxDims.width) : 1) : (unitType === 'pallet' ? Math.floor(unitDimensions.width / currentBoxDims.width) : 1),
                        rows: unitType === 'pallet' ? Math.floor(unitDimensions.length / currentBoxDims.length) : 1,
                        layers: unitType === 'box' && layerConfig && layerConfig.includes('x') ? (itemsPerUnit > 1 ? Math.floor(unitDimensions.height / currentBoxDims.height) : 1) : (unitType === 'pallet' ? Math.floor((unitDimensions.height - PALLET_BASE_HEIGHT_MM) / currentBoxDims.height) : 1)
                    }
                });
                remainingItemsTotal -= Math.min(itemsPerUnit, remainingItemsTotal);
                unitsPlaced++;
                remainingUnits--;
            }

            const itemsInThisLoad = placements.reduce((sum, item) => sum + (item.itemCount || 0), 0);
            const actualLoadVolume = placements.reduce((sum, item) => sum + (item.dimensions.length * item.dimensions.width * item.dimensions.height), 0);
            const containerVolume = container.dimensions.length * container.dimensions.width * container.dimensions.height;
            const utilization = (actualLoadVolume / containerVolume) * 100;

            loads.push({
                id: loadId++,
                items: placements,
                utilization,
                itemCount: itemsInThisLoad,
                type: isFull ? 'full' : 'partial'
            });
            totalItemsInScenario += itemsInThisLoad;
            // totalActualUsedVolume += actualLoadVolume; // Removed
        }
        // maxItemsPacked = totalItemsInScenario;
        // bestUsedVolume = totalActualUsedVolume; // Removed
        bestResult = {
            loads,
            totalItems: totalItemsInScenario,
            totalContainers: loads.length,
            unpackedItems: quantity - totalItemsInScenario,
            packedBoxDimensions: currentBoxDims,
            errors: errors.length > 0 ? errors : [],
            actualUsedVolume: totalActualUsedVolume
        };
    }


    if (!bestResult) {
        return {
            loads: [],
            totalItems: 0,
            totalContainers: 0,
            unpackedItems: quantity,
            errors: errors.length > 0 ? errors : ['No valid packing found for selected usage.']
        };
    }

    return bestResult;
}




/**
 * Validates that a placed item has physical support beneath it
 */
const hasPhysicalSupport = (
    item: PlacedItem,
    load: ContainerLoad,
    marginH: number
): boolean => {
    const itemBottom = item.position[1] - item.dimensions.height / 2;
    const itemLeft = item.position[0] - item.dimensions.length / 2;
    const itemRight = item.position[0] + item.dimensions.length / 2;
    const itemBack = item.position[2] - item.dimensions.width / 2;
    const itemFront = item.position[2] + item.dimensions.width / 2;

    // If on ground level, always supported
    if (Math.abs(itemBottom - marginH) < 10) {
        return true;
    }

    // Check if there's support beneath
    // Support must cover at least 80% of the item's footprint
    let supportedArea = 0;
    const itemFootprint = (itemRight - itemLeft) * (itemFront - itemBack);

    for (const other of load.items) {
        if (other === item) continue;

        const otherTop = other.position[1] + other.dimensions.height / 2;
        const otherLeft = other.position[0] - other.dimensions.length / 2;
        const otherRight = other.position[0] + other.dimensions.length / 2;
        const otherBack = other.position[2] - other.dimensions.width / 2;
        const otherFront = other.position[2] + other.dimensions.width / 2;

        // Check if this item is directly below (within tolerance)
        if (Math.abs(otherTop - itemBottom) > 10) continue;

        // Calculate overlap area
        const overlapLeft = Math.max(itemLeft, otherLeft);
        const overlapRight = Math.min(itemRight, otherRight);
        const overlapBack = Math.max(itemBack, otherBack);
        const overlapFront = Math.min(itemFront, otherFront);

        if (overlapRight > overlapLeft && overlapFront > overlapBack) {
            const area = (overlapRight - overlapLeft) * (overlapFront - overlapBack);
            supportedArea += area;
        }
    }

    // Require at least 80% support coverage
    return supportedArea >= itemFootprint * 0.8;
};

export const calculatePacking = (
    container: Container,
    materials: import('./types').Material[],
    isCombined: boolean = false,
    margins: { length?: number; width?: number; height?: number } = { length: 20, width: 20, height: 20 },
    packingMode: import('./types').PackingMode = 'SEQUENTIAL',
    enableTopUp: boolean = false,
    enableFullMix: boolean = false,
    fullMixRotations?: import('./types').FullMixRotations
): PackingResult => {
    const activeMaterials = deepClone(materials.filter((m: import('./types').Material) => m.active && m.quantity > 0));

    // Capture initial quantities before packing mutates them (crucial for pipeline)
    const initialQuantities = new Map<number, number>();
    activeMaterials.forEach((m: import('./types').Material) => initialQuantities.set(m.id, m.quantity));

    /**
     * MATERIAL ORDER LAW (IMMUTABLE):
     * Materials are processed STRICTLY in the order provided by the input array.
     * No sorting, shuffling, or heuristics are allowed to reorder materials.
     * This ensures deterministic output: Input [A, B] will always pack A, then B.
     * Re-optimizing previous placements is FORBIDDEN.
     */

    if (activeMaterials.length === 0) {
        return {
            totalItems: 0,
            totalContainers: 0,
            loads: [],
            containerDimensions: container.dimensions,
            unpackedItems: 0,
            errors: []
        };
    }



    const calculateStats = (res: PackingResult) => {
        let totalPallets = 0;
        let totalLots = 0;

        res.loads.forEach((load: ContainerLoad) => {
            const uniqueBasePositions = new Set<string>();
            load.items.forEach((item: PlacedItem) => {
                if (item.type === 'pallet') {
                    totalPallets++;
                }
                const mat = activeMaterials.find((m: import('./types').Material) => m.id === item.materialId);
                const hasStrictConfig = mat && mat.layerConfig && mat.layerConfig.trim();

                if (hasStrictConfig && item.type === 'pallet' && item.position?.length === 3) {
                    const x = Math.round(item.position[0]);
                    const z = Math.round(item.position[2]);
                    const centerY = item.position[1];
                    const expectedBaseY = item.dimensions.height / 2;
                    const diff = Math.abs(centerY - expectedBaseY);

                    if (diff < PALLET_POSITION_TOLERANCE_MM) {
                        const key = `${x}_${z}`;
                        uniqueBasePositions.add(key);
                    }
                }
            });
            totalLots += uniqueBasePositions.size;
        });

        return { ...res, totalPallets, totalLots };
    };

    // --------------------------------------------------------------------------
    // PHASE 7: FAST PATH (Restored Invariant)
    // Hard Gate for Single Material, Non-Combined Packing
    // --------------------------------------------------------------------------
    if (!isCombined && activeMaterials.length === 1) {
        const mat = activeMaterials[0];
        const box = deepClone(mat.box);
        const marginL = margins.length ?? DEFAULT_MARGIN_MM;
        const marginW = margins.width ?? DEFAULT_MARGIN_MM;
        const marginH = margins.height ?? DEFAULT_MARGIN_MM;
        const errors: string[] = [];

        // 1. Prepare Orientations
        const allPermutations: Dimensions[] = [
            { length: box.dimensions.length, width: box.dimensions.width, height: box.dimensions.height },
            { length: box.dimensions.length, width: box.dimensions.height, height: box.dimensions.width },
            { length: box.dimensions.width, width: box.dimensions.length, height: box.dimensions.height },
            { length: box.dimensions.width, width: box.dimensions.height, height: box.dimensions.length },
            { length: box.dimensions.height, width: box.dimensions.length, height: box.dimensions.width },
            { length: box.dimensions.height, width: box.dimensions.width, height: box.dimensions.length }
        ];

        const allowedOrientations: Dimensions[] = [];
        if (box.allowedRotations.y) { allowedOrientations.push(allPermutations[0]); allowedOrientations.push(allPermutations[2]); }
        if (box.allowedRotations.x) { allowedOrientations.push(allPermutations[3]); allowedOrientations.push(allPermutations[5]); }
        if (box.allowedRotations.z) { allowedOrientations.push(allPermutations[1]); allowedOrientations.push(allPermutations[4]); }
        if (allowedOrientations.length === 0) allowedOrientations.push(allPermutations[0]);

        // 2. Select Dimensions
        let selectionTarget: Container;
        if (mat.pallet.usePallet) {
            selectionTarget = {
                name: 'Pallet Proxy',
                type: 'custom',
                dimensions: {
                    length: mat.pallet.dimensions.length,
                    width: mat.pallet.dimensions.width,
                    height: mat.pallet.maxLoadHeight
                },
            };
        } else {
            selectionTarget = {
                ...container,
                dimensions: {
                    length: (container.dimensions.length - marginL * 2),
                    width: (container.dimensions.width - marginW * 2),
                    height: (container.dimensions.height - marginH * 2)
                }
            };
        }
        const bestDims = selectBestOrientation(selectionTarget, box, allowedOrientations);

        // 3. Determine Unit Dimensions
        let unitDimensions: Dimensions;
        let itemsPerUnit = 1;
        let unitType: 'box' | 'pallet' = 'box';
        // Capture layout for accurate grid reporting
        let layoutCols = 1;
        let layoutRows = 1;

        if (mat.pallet.usePallet) {
            unitType = 'pallet';
            const pDims = mat.pallet.dimensions;

            // Try to parse layerConfig first (e.g., "6x2")
            let cols, rows;
            const parsed = parseLayerConfig(mat.layerConfig);

            if (parsed && parsed.horizontal > 0 && parsed.vertical > 0) {
                // Use user-specified configuration
                cols = parsed.horizontal;
                rows = parsed.vertical;
            } else {
                // Fallback to autocalculation based on box dimensions
                cols = Math.floor(pDims.length / bestDims.length);
                rows = Math.floor(pDims.width / bestDims.width);
            }

            // Always calculate layers based on available height
            const availH = mat.pallet.maxLoadHeight - PALLET_BASE_HEIGHT_MM;
            const layers = Math.floor(availH / bestDims.height);

            if (cols > 0 && rows > 0 && layers > 0) {
                itemsPerUnit = cols * rows * layers;
                layoutCols = cols;
                layoutRows = rows;
                unitDimensions = {
                    length: pDims.length,
                    width: pDims.width,
                    height: PALLET_BASE_HEIGHT_MM + (layers * bestDims.height)
                };
            } else {
                return { loads: [], totalItems: 0, totalContainers: 0, unpackedItems: mat.quantity, errors: ['Pallet configuration invalid.'], containerDimensions: container.dimensions };
            }

        } else {
            const parsed = parseLayerConfig(mat.layerConfig);
            if (parsed) {
                const maxH = Math.floor((container.dimensions.width - marginW * 2) / bestDims.width);
                const maxV = Math.floor((container.dimensions.height - marginH * 2) / bestDims.height);
                const finalH = Math.min(parsed.horizontal, maxH);
                const finalV = Math.min(parsed.vertical, maxV);
                itemsPerUnit = finalH * finalV;
                layoutCols = finalH; // For box stacks, cols ~ width factor?
                layoutRows = 1;      // Rows depth?
                // Wait, if 4x3 stack (H x V):
                // Width = 4 * boxW
                // Height = 3 * boxH
                // So grid cols should be 4, grid rows should be 1, layers should be 3.
                layoutCols = finalH;
                layoutRows = 1;

                unitDimensions = {
                    length: bestDims.length,
                    width: finalH * bestDims.width,
                    height: finalV * bestDims.height
                };
            } else {
                unitDimensions = bestDims;
                itemsPerUnit = 1;
            }
        }

        // 4. Prepare volume configuration for packGridCore
        let effH = container.dimensions.height - marginH * 2;
        if (unitType === 'pallet') {
            if (mat.pallet.stackPallets) effH = Math.min(effH, MAX_PALLET_STACK_HEIGHT * unitDimensions.height);
            else effH = unitDimensions.height;
        } else if (mat.layerConfig && mat.layerConfig.toLowerCase().includes('x')) {
            effH = unitDimensions.height;
        }

        const volume: GridVolume = {
            // packGridCore's INTERNAL coordinate system: X=Width, Y=Length, Z=Height
            // So origin must be: x=widthMargin, y=lengthMargin, z=heightMargin
            origin: { x: marginW, y: marginL, z: marginH },
            bounds: {
                length: container.dimensions.length - marginL * 2,
                height: effH,
                width: container.dimensions.width - marginW * 2
            }
        };

        // 5. Construct Loads with STRICT QUANTITY ENFORCEMENT (Phase 7.8)
        // Each container gets its own independent grid via separate packGridCore calls
        let remainingQty = mat.quantity;
        const loads: import('./types').ContainerLoad[] = [];
        let containerIndex = 0;

        while (remainingQty > 0) {
            // Call packGridCore for THIS container (independent grid)
            const gridPlacements = packGridCore(volume, unitDimensions);

            if (gridPlacements.length === 0) {
                return { loads: [], totalItems: 0, totalContainers: 0, unpackedItems: mat.quantity, errors: ['Item too large for container.'], containerDimensions: container.dimensions };
            }

            const capacity = gridPlacements.length;

            // QUANTITY GOVERNOR: Never exceed remainingQty
            const itemsToPlace = Math.min(capacity * itemsPerUnit, remainingQty);
            const unitsToPlace = Math.ceil(itemsToPlace / itemsPerUnit);

            // Slice placements to exact count needed
            const slicedPlacements = gridPlacements.slice(0, unitsToPlace);

            const placements: import('./types').PlacedItem[] = [];
            let itemsPlaced = 0;

            for (let i = 0; i < slicedPlacements.length; i++) {
                const p = slicedPlacements[i];
                const itemsInThisUnit = Math.min(itemsPerUnit, remainingQty - itemsPlaced);

                placements.push({
                    position: kernelToPlacedPosition(p.position),
                    rotation: [0, 0, 0],
                    dimensions: p.dimensions,
                    type: unitType,
                    itemCount: itemsInThisUnit,
                    materialId: mat.id,
                    grid: {
                        cols: (unitType === 'pallet')
                            ? layoutCols
                            : (itemsPerUnit > 1 ? Math.floor(unitDimensions.width / bestDims.width) : 1),
                        rows: (unitType === 'pallet')
                            ? layoutRows
                            : 1,
                        layers: (unitType === 'pallet')
                            ? Math.floor((unitDimensions.height - PALLET_BASE_HEIGHT_MM) / bestDims.height)
                            : (itemsPerUnit > 1 ? Math.floor(unitDimensions.height / bestDims.height) : 1)
                    },
                    isPalletBase: unitType === 'pallet'
                });

                itemsPlaced += itemsInThisUnit;
            }

            // Phase 7.9: TRUTHFUL load metadata
            // "full" means placedCount === capacity
            const placedCount = placements.length;
            const isFull = placedCount === gridPlacements.length;

            // Utilization from ACTUAL placed items, not theoretical capacity
            const loadVol = placements.reduce((s, i) => s + (i.dimensions.length * i.dimensions.width * i.dimensions.height), 0);
            const contVol = container.dimensions.length * container.dimensions.width * container.dimensions.height;

            loads.push({
                id: containerIndex + 1,
                items: placements,
                itemCount: itemsPlaced,
                utilization: (loadVol / contVol) * 100,
                type: isFull ? 'full' : 'partial'
            });

            remainingQty -= itemsPlaced;
            containerIndex++;

            // Safety: prevent infinite loop
            if (containerIndex > 1000) {
                return { loads: [], totalItems: 0, totalContainers: 0, unpackedItems: mat.quantity, errors: ['Infinite loop detected in quantity enforcement'], containerDimensions: container.dimensions };
            }
        }
        // Calculate actualUsedVolume using actual box dimensions, not unit dimensions
        const boxVolume = bestDims.length * bestDims.width * bestDims.height;
        // let totalActualUsedVolume = mat.quantity * boxVolume;

        // --------------------------------------------------------------------------
        // POST-PROCESSING PASSES (Pipeline Architecture)
        // --------------------------------------------------------------------------
        // Now using robust geometry-based activation and stateful quantity tracking
        // to prevent phantom boxes and ensuring strict order.
        let finalLoads = loads;

        if (enableTopUp || enableFullMix) {
            // Use the shared pipeline implementation
            // FIX: Ensure we pass the ORIGINAL quantity, not a mutated one
            const pipelineMat = { ...mat, quantity: initialQuantities.get(mat.id)! };

            const pipelineResult = runPostProcessingPipeline(
                loads,
                pipelineMat,
                container,
                margins,
                enableTopUp,
                enableFullMix,
                fullMixRotations
            );

            finalLoads = pipelineResult.loads;
        }

        // Phase 7: Recalculate Stats from Final Loads (Source of Truth)
        const finalTotalItems = finalLoads.reduce((s, l) => s + l.itemCount, 0);
        const finalUnpacked = mat.quantity - finalTotalItems;
        const finalVolume = finalTotalItems * boxVolume;

        return calculateStats({
            loads: finalLoads,
            totalItems: finalTotalItems,
            totalContainers: finalLoads.length,
            unpackedItems: finalUnpacked,
            containerDimensions: container.dimensions,
            errors,
            actualUsedVolume: finalVolume,
            packedBoxDimensions: bestDims
        });
    }

    // --------------------------------------------------------------------------
    // PHASE 8: ISOLATED MODE FUNCTIONS
    // --------------------------------------------------------------------------

    /**
     * Mode 1: SEQUENTIAL
     * Baseline mode: materials packed in strict input order, no cross-material stacking
     */
    function packSequential(
        cont: Container,
        mats: import('./types').Material[],
        marg: { length?: number; width?: number; height?: number },
        _combined: boolean
    ): PackingResult {
        const allLoads: ContainerLoad[] = [];
        let totalItemsPlaced = 0;
        let totalUnpacked = 0;
        const allErrors: string[] = [];
        let totalVolume = 0;

        // Process each material independently - NO CROSS-MATERIAL INTERACTION
        for (const mat of mats) {
            // Use the single-material fast path logic for each material
            const result = calculatePacking(cont, [mat], false, marg, 'SEQUENTIAL');

            // Merge results
            result.loads.forEach(load => {
                allLoads.push({
                    ...load,
                    id: allLoads.length + 1  // Re-index
                });
            });

            totalItemsPlaced += result.totalItems;
            totalUnpacked += result.unpackedItems;
            totalVolume += result.actualUsedVolume || 0;
            if (result.errors) allErrors.push(...result.errors);
        }

        return {
            loads: allLoads,
            totalItems: totalItemsPlaced,
            totalContainers: allLoads.length,
            unpackedItems: totalUnpacked,
            containerDimensions: cont.dimensions,
            actualUsedVolume: totalVolume,
            ...(allErrors.length > 0 ? { errors: allErrors } : {})
        };
    }

    /**
     * Mode 2: SMART_STACK
     * Sequential-first, then vertical continuation if safe
     * RULES:
     * - Materials processed in order
     * - Next material may stack on top IF dimensions safe (length <= prev.length AND width <= prev.width)
     * - Vertical only (Y+), never side-mix (X/Z)
     * - Uses packGridCore for each layer
     * - Deterministic and repeatable
     */
    /**
 * SMART_STACK MODE — LOCKED
 * Vertical-only continuation
 * No side-mixing
 * Deterministic
 * Regression-guarded (7 tests)
 */
    function packSmartStack(
        cont: Container,
        mats: import('./types').Material[],
        marg: { length?: number; width?: number; height?: number },
        _combined: boolean
    ): PackingResult {
        const marginL = marg.length ?? DEFAULT_MARGIN_MM;
        const marginW = marg.width ?? DEFAULT_MARGIN_MM;
        const marginH = marg.height ?? DEFAULT_MARGIN_MM;

        const allLoads: ContainerLoad[] = [];
        let totalItemsPlaced = 0;
        let totalUnpacked = 0;
        const allErrors: string[] = [];
        let totalVolume = 0;

        // Current container state for vertical continuation
        let currentContainerItems: import('./types').PlacedItem[] = [];
        let lastLayerTopY = marginH; // Start from floor
        let lastLayerFootprint: { length: number; width: number; originX: number; originZ: number } | null = null;
        let remainingHeight = cont.dimensions.height - marginH * 2;
        let containerIndex = 0;

        // Helper to close current container and start fresh
        const closeCurrentContainer = () => {
            if (currentContainerItems.length > 0) {
                // const placedCount = currentContainerItems.length;
                // const capacity = placedCount; // For SMART_STACK, capacity is what we achieved
                const isFull = remainingHeight < 100; // Consider full if <100mm remaining
                const loadVol = currentContainerItems.reduce((s, i) => s + (i.dimensions.length * i.dimensions.width * i.dimensions.height), 0);
                const contVol = cont.dimensions.length * cont.dimensions.width * cont.dimensions.height;
                const itemCount = currentContainerItems.reduce((sum, item) => sum + (item.itemCount || 1), 0);

                allLoads.push({
                    id: allLoads.length + 1,
                    items: currentContainerItems,
                    itemCount: itemCount,
                    utilization: (loadVol / contVol) * 100,
                    type: isFull ? 'full' : 'partial'
                });
            }
            // Reset for next container
            currentContainerItems = [];
            lastLayerTopY = marginH;
            lastLayerFootprint = null;
            remainingHeight = cont.dimensions.height - marginH * 2;
            containerIndex++;
        };

        // Process each material
        for (const mat of mats) {
            // Use single-material fast path to determine best orientation and capacity
            const tempResult = calculatePacking(cont, [mat], false, marg, 'SEQUENTIAL');

            if (tempResult.loads.length === 0 || tempResult.loads[0].items.length === 0) {
                allErrors.push(`Material ${mat.id}: too large for container`);
                totalUnpacked += mat.quantity;
                continue;
            }

            const firstLoad = tempResult.loads[0];
            const firstItem = firstLoad.items[0];
            const bestDims = firstItem.dimensions; // These are the oriented dimensions
            const unitType = firstItem.type;
            const itemsPerUnit = firstItem.itemCount || 1;

            // Pack this material
            let remainingQty = mat.quantity;
            let materialItemsPlaced = 0;

            // SMART_STACK: Single attempt per material (no retries, no alternate volumes)
            // SMART_STACK: Single attempt per material (no retries, no alternate volumes)
            // But with Container Continuity: Try Stack -> Try Floor -> New Container
            while (remainingQty > 0) {
                // SMART_STACK: Three-step placement logic
                // 1. Try Vertical Stacking (if compatible)
                // 2. Try Floor Placement in current container (if space exists)
                // 3. New Container (if 1 and 2 fail)

                let placedInCurrent = false;
                let itemsPlacedInThisStep = 0;

                // --- ATTEMPT 1: Vertical Stacking ---
                let canStack = false;
                if (lastLayerFootprint !== null && currentContainerItems.length > 0) {
                    const fitsLength = bestDims.length <= lastLayerFootprint.length;
                    const fitsWidth = bestDims.width <= lastLayerFootprint.width;
                    const fitsHeight = bestDims.height <= remainingHeight;
                    canStack = fitsLength && fitsWidth && fitsHeight;
                }

                if (canStack && lastLayerFootprint) {
                    // NOTE: packGridCore uses kernel space [W,L,H], not placed space [L,H,W]
                    const stackVolume = {
                        origin: {
                            x: lastLayerFootprint.originZ,  // kernel.x = placed.z (Width)
                            y: lastLayerFootprint.originX,  // kernel.y = placed.x (Length)
                            z: lastLayerTopY                // kernel.z = placed.y (Height)
                        },
                        bounds: {
                            length: lastLayerFootprint.length,
                            width: lastLayerFootprint.width,
                            height: remainingHeight
                        }
                    };

                    // Guard: Invariant check
                    if (stackVolume.bounds.length !== lastLayerFootprint.length ||
                        stackVolume.bounds.width !== lastLayerFootprint.width) {
                        canStack = false;
                    } else {
                        // Attempt pack
                        const stackPlacements = packGridCore(stackVolume, bestDims);
                        if (stackPlacements.length > 0) {
                            // SUCCESS: Stacking
                            const capacity = stackPlacements.length;
                            const itemsToPlace = Math.min(capacity * itemsPerUnit, remainingQty);
                            const unitsToPlace = Math.ceil(itemsToPlace / itemsPerUnit);
                            const slicedPlacements = stackPlacements.slice(0, unitsToPlace);

                            // Commit Stacking
                            for (const p of slicedPlacements) {
                                const placedPos = kernelToPlacedPosition(p.position);
                                const itemsInThisUnit = Math.min(itemsPerUnit, remainingQty - itemsPlacedInThisStep);

                                currentContainerItems.push({
                                    position: placedPos,
                                    rotation: [0, 0, 0],
                                    dimensions: p.dimensions,
                                    type: unitType,
                                    itemCount: itemsInThisUnit,
                                    materialId: mat.id,
                                    packingMode: 'SMART_STACK'
                                });
                                itemsPlacedInThisStep += itemsInThisUnit;
                            }

                            remainingQty -= itemsPlacedInThisStep;
                            materialItemsPlaced += itemsPlacedInThisStep;
                            placedInCurrent = true;
                        }
                    }
                }

                // --- ATTEMPT 2: Floor Placement (Fallback) ---
                if (!placedInCurrent && remainingQty > 0) {
                    // Try to place on the floor of the current container
                    // Calculate used length (Placed X)
                    let maxPlacedLength = marginL;
                    if (currentContainerItems.length > 0) {
                        for (const item of currentContainerItems) {
                            const itemEndL = item.position[0] + item.dimensions.length / 2;
                            if (itemEndL > maxPlacedLength) maxPlacedLength = itemEndL;
                        }
                    }

                    // Define Floor Volume
                    // Origin: x=marginW (Kernel Width), y=maxPlacedLength (Kernel Length), z=marginH (Kernel Height)
                    // Bounds: available length, width, height
                    const floorVolume = {
                        origin: {
                            x: marginW,
                            y: maxPlacedLength,
                            z: marginH
                        },
                        bounds: {
                            length: cont.dimensions.length - maxPlacedLength - marginL,
                            width: cont.dimensions.width - marginW * 2,
                            height: cont.dimensions.height - marginH * 2
                        }
                    };

                    // Check if items fit at all
                    if (floorVolume.bounds.length >= bestDims.length &&
                        floorVolume.bounds.width >= bestDims.width &&
                        floorVolume.bounds.height >= bestDims.height) {

                        const floorPlacements = packGridCore(floorVolume, bestDims);

                        if (floorPlacements.length > 0) {
                            // SUCCESS: Floor Placement
                            const capacity = floorPlacements.length;
                            const itemsToPlace = Math.min(capacity * itemsPerUnit, remainingQty);
                            const unitsToPlace = Math.ceil(itemsToPlace / itemsPerUnit);
                            const slicedPlacements = floorPlacements.slice(0, unitsToPlace);

                            // Commit Floor Placement
                            for (const p of slicedPlacements) {
                                const placedPos = kernelToPlacedPosition(p.position);
                                const itemsInThisUnit = Math.min(itemsPerUnit, remainingQty - itemsPlacedInThisStep);

                                currentContainerItems.push({
                                    position: placedPos,
                                    rotation: [0, 0, 0],
                                    dimensions: p.dimensions,
                                    type: unitType,
                                    itemCount: itemsInThisUnit,
                                    materialId: mat.id,
                                    packingMode: 'SMART_STACK'
                                });
                                itemsPlacedInThisStep += itemsInThisUnit;
                            }

                            remainingQty -= itemsPlacedInThisStep;
                            materialItemsPlaced += itemsPlacedInThisStep;
                            placedInCurrent = true;
                        }
                    }
                }

                // --- ATTEMPT 3: New Container ---
                if (!placedInCurrent) {
                    if (currentContainerItems.length > 0) {
                        closeCurrentContainer();
                        // Reset
                        lastLayerTopY = marginH;
                        remainingHeight = cont.dimensions.height - marginH * 2;
                        lastLayerFootprint = null;
                        continue; // Retry loop with fresh container
                    } else {
                        // Item too big for empty container
                        break; // Fatal for this material
                    }
                }

                // --- UPDATE STATE (Ground Truth) ---
                if (placedInCurrent && currentContainerItems.length > 0) {
                    const placedItemsForFootprint = currentContainerItems;
                    const footprintMinX = Math.min(...placedItemsForFootprint.map(p => p.position[0] - p.dimensions.length / 2));
                    const footprintMaxX = Math.max(...placedItemsForFootprint.map(p => p.position[0] + p.dimensions.length / 2));
                    const footprintMinZ = Math.min(...placedItemsForFootprint.map(p => p.position[2] - p.dimensions.width / 2));
                    const footprintMaxZ = Math.max(...placedItemsForFootprint.map(p => p.position[2] + p.dimensions.width / 2));
                    const footprintTopY = Math.max(...placedItemsForFootprint.map(p => p.position[1] + p.dimensions.height / 2));

                    lastLayerTopY = footprintTopY;
                    lastLayerFootprint = {
                        length: footprintMaxX - footprintMinX,
                        width: footprintMaxZ - footprintMinZ,
                        originX: footprintMinX,
                        originZ: footprintMinZ
                    };
                    remainingHeight = (cont.dimensions.height - marginH) - lastLayerTopY;

                    totalItemsPlaced += itemsPlacedInThisStep;
                    totalVolume += itemsPlacedInThisStep * (bestDims.length * bestDims.width * bestDims.height);
                }

                // Safety: prevent infinite loop
                if (containerIndex > 1000) {
                    allErrors.push('Infinite loop detected in SMART_STACK');
                    break;
                }
            }

            totalUnpacked += remainingQty;
        }

        // Close final container if any items remain
        if (currentContainerItems.length > 0) {
            closeCurrentContainer();
        }

        return {
            loads: allLoads,
            totalItems: totalItemsPlaced,
            totalContainers: allLoads.length,
            unpackedItems: totalUnpacked,
            containerDimensions: cont.dimensions,
            actualUsedVolume: totalVolume,
            ...(allErrors.length > 0 ? { errors: allErrors } : {})
        };
    }

    /**
     * Mode 3: TETRIS
     * Greedy box-level filling, ignores material boundaries
     * TODO: Implement in Step 5
     */
    function packTetris(
        cont: Container,
        mats: import('./types').Material[],
        _marg: { length?: number; width?: number; height?: number }
    ): PackingResult {
        // TODO: Step 5 implementation
        // For now, return empty result
        return {
            loads: [],
            totalItems: 0,
            totalContainers: 0,
            unpackedItems: mats.reduce((sum, m) => sum + m.quantity, 0),
            containerDimensions: cont.dimensions,
            errors: ['TETRIS mode not yet implemented']
        };
    }

    // --------------------------------------------------------------------------
    // PHASE 8: MIXED-MATERIAL MODE ROUTER
    // Explicit mode routing - NO FALLTHROUGH, NO SHARED LOGIC
    // --------------------------------------------------------------------------
    /**
     * PHASE 8 LOCK:
     * Packing modes are isolated.
     * No cross-mode logic allowed.
     * Kernel + Quantity Governor are immutable.
     */

    // Mode Router: Hard switch based on packingMode
    // Each mode has its own isolated function
    if (activeMaterials.length > 1 || isCombined) {
        switch (packingMode) {
            case 'SEQUENTIAL':
                return packSequential(container, activeMaterials, margins, isCombined);

            case 'SMART_STACK':
                return packSmartStack(container, activeMaterials, margins, isCombined);

            case 'TETRIS':
                return packTetris(container, activeMaterials, margins);

            default:
                // Fallback to SEQUENTIAL if unknown mode
                return packSequential(container, activeMaterials, margins, isCombined);
        }
    }

    // If we reach here, it's a fallback (should not happen with fast path)
    const runSequence = (sequence: import('./types').Material[]): PackingResult => {
        let loads: ContainerLoad[] = [];
        let totalItems = 0;
        let unpackedItems = 0;
        let errors: string[] = [];
        let totalActualUsedVolume = 0;
        let packedBoxDimensions: Dimensions | undefined;
        let floatingItemRepackAttempts = new Map<number, number>(); // Track repack attempts per material
        const MAX_REPACK_ATTEMPTS = 3;

        for (let i = 0; i < sequence.length; i++) {
            const mat = sequence[i];

            // Combined packing: try to fit into existing containers using shelf-based packing
            // Materials with layer config will use ground_horizontal shelves (floor space)
            // and follow their own stacking logic from there
            if (isCombined && loads.length > 0) {



                // Iterate through ALL existing loads to find space (Retrospective Packing)
                // STRATEGY: Iterate backwards to fill newest container first, keeping materials concentrated
                // This reduces material fragmentation across multiple containers
                for (let loadIndex = loads.length - 1; loadIndex >= 0; loadIndex--) {
                    let currentLoad = loads[loadIndex];


                    // --- STRATEGY 0: CLEANUP ---
                    // Remove ghost items, zero-volume items, or items clearly out of bounds that might block packing
                    // This is a safety net for state corruption
                    currentLoad.items = currentLoad.items.filter(item => {
                        const vol = item.dimensions.length * item.dimensions.width * item.dimensions.height;
                        if (vol <= 0.001) return false; // Remove zero/negative volume

                        // Check bounds (with tolerance)
                        const itemRight = item.position[0] + item.dimensions.length / 2;
                        const itemTop = item.position[1] + item.dimensions.height / 2;
                        const itemFront = item.position[2] + item.dimensions.width / 2;

                        if (itemRight > container.dimensions.length + 100) return false; // Way out of bounds
                        if (itemTop > container.dimensions.height + 100) return false;
                        if (itemFront > container.dimensions.width + 100) return false;

                        return true;
                    });

                    // --- STRATEGY 1: SHELF PACKING ---
                    const shelves = findAvailableShelves(currentLoad, container.dimensions, margins);

                    // Sort Shelves Priority: Floor space first
                    shelves.sort((a, b) => {
                        const typePriority = { ground_horizontal: 0, side_strip: 0, gap: 1, peak: 2 }; // Floor space first

                        const pA = typePriority[a.type];
                        const pB = typePriority[b.type];
                        if (pA !== pB) return pA - pB;
                        // If same priority, prefer lower Y (closer to ground), then lower Z (closer to back)
                        if (a.y !== b.y) return a.y - b.y;
                        return (a.z || 0) - (b.z || 0);
                    });


                    for (const shelf of shelves) {

                        // Skip if shelf is too small for any orientation of the box
                        const shelfLength = shelf.endX - shelf.startX;


                        const boxMinDim = Math.min(
                            mat.box.dimensions.length,
                            mat.box.dimensions.width,
                            mat.box.dimensions.height
                        );

                        if (shelfLength < boxMinDim) {
                            continue; // Box won't fit on this shelf
                        }

                        // For elevated shelves, we must be extra careful
                        const isElevated = shelf.type === 'peak' || shelf.type === 'gap';

                        // FIX: Clone box to prevent mutation bleed
                        const boxToPack = deepClone(mat.box);
                        const marginL = margins.length ?? DEFAULT_MARGIN_MM;

                        // CRITICAL: Pass the EXACT support length, not more
                        // The packMaterial function must NOT place items beyond this
                        const supportLength = isElevated ? shelfLength : (shelf.endX - shelf.startX);

                        const res = packMaterial(
                            boxToPack, container, mat.pallet, mat.quantity, mat.layerConfig, mat.id,
                            shelf.startX - marginL, currentLoad, { ...margins, height: 0 }, shelf.y, shelf.z || 0,
                            false, // Do NOT create new containers here
                            supportLength // Limit packing to shelf/support length
                        );

                        if (res.loads.length > 0 && res.loads[0].items.length > currentLoad.items.length) {
                            // Additional validation: Remove any items that extend beyond support for ANY shelf
                            // Phase 7: Strict Bounds Validation (Floating Box Fix)
                            const existingItemCount = currentLoad.items.length;
                            const allItems = res.loads[0].items;
                            const newItems = allItems.slice(existingItemCount);

                            const keptNewItems = newItems.filter(item => {
                                // Check if item is within support bounds
                                const itemRight = item.position[0] + item.dimensions.length / 2;
                                const itemLeft = item.position[0] - item.dimensions.length / 2;

                                // Item must be fully within support region (with small tolerance)
                                return itemLeft >= shelf.startX - 1 && itemRight <= shelf.endX + 1;
                            });

                            // If we had to filter items, update the result
                            if (keptNewItems.length < newItems.length) {
                                const removed = newItems.length - keptNewItems.length;
                                res.loads[0].items = [...allItems.slice(0, existingItemCount), ...keptNewItems];
                                res.totalItems -= removed;
                                res.unpackedItems += removed;

                                // Recalculate utilization for the filtered load
                                const loadVol = res.loads[0].items.reduce((sum, item) => sum + item.dimensions.length * item.dimensions.width * item.dimensions.height, 0);
                                const containerVol = container.dimensions.length * container.dimensions.width * container.dimensions.height;
                                res.loads[0].utilization = (loadVol / containerVol) * 100;
                                res.loads[0].itemCount = res.loads[0].items.reduce((sum, item) => sum + (item.itemCount || 0), 0);
                            }


                            // Update the specific load
                            loads[loadIndex] = res.loads[0];
                            // FIX: Update currentLoad reference
                            currentLoad = loads[loadIndex];

                            // If packMaterial created NEW loads (overflow), append them
                            if (res.loads.length > 1) {
                                loads = [...loads, ...res.loads.slice(1)];
                            }

                            totalItems += res.totalItems;
                            unpackedItems += res.unpackedItems;
                            totalActualUsedVolume += (res.actualUsedVolume || 0);
                            errors = [...errors, ...res.errors];
                            if (i === 0) packedBoxDimensions = res.packedBoxDimensions;

                            // Update remaining quantity for next iteration/material
                            mat.quantity = res.unpackedItems;

                            // If we fully packed this material, break out of shelf loop and load loop
                            if (mat.quantity <= 0) break;
                        }
                    }
                    if (mat.quantity <= 0) break;
                }



                // === FLOATING ITEM VALIDATION (MOVED) ===
                const marginH = margins.height ?? DEFAULT_MARGIN_MM;
                // Validate loads immediately to recover floating items
                for (const load of loads) {
                    const validItems = load.items.filter(item =>
                        hasPhysicalSupport(item, load, marginH)
                    );

                    if (validItems.length < load.items.length) {
                        const floatingCount = load.items.length - validItems.length;

                        // Check if we've exceeded max repack attempts for this material
                        const currentAttempts = floatingItemRepackAttempts.get(mat.id) || 0;
                        if (currentAttempts >= MAX_REPACK_ATTEMPTS) {
                            console.warn(`Material ${mat.id}: Max repack attempts (${MAX_REPACK_ATTEMPTS}) exceeded. ${floatingCount} items will remain unpacked due to lack of physical support.`);
                            // Don't add back to quantity - treat as permanently unpacked
                            const floatingItems = load.items.filter(item =>
                                !hasPhysicalSupport(item, load, marginH)
                            );
                            const floatingItemCount = floatingItems.reduce(
                                (sum, item) => sum + (item.itemCount || 1), 0
                            );
                            totalItems -= floatingItemCount;
                            unpackedItems += floatingItemCount;

                            load.items = validItems;
                            load.itemCount = validItems.reduce(
                                (sum, item) => sum + (item.itemCount || 0), 0
                            );
                            const loadVol = validItems.reduce(
                                (sum, item) => sum + item.dimensions.length * item.dimensions.width * item.dimensions.height,
                                0
                            );
                            const containerVol = container.dimensions.length * container.dimensions.width * container.dimensions.height;
                            load.utilization = (loadVol / containerVol) * 100;
                            continue; // Skip repacking for this load
                        }

                        // Move floating items back to unpacked
                        const floatingItems = load.items.filter(item =>
                            !hasPhysicalSupport(item, load, marginH)
                        );

                        const floatingItemCount = floatingItems.reduce(
                            (sum, item) => sum + (item.itemCount || 1), 0
                        );

                        // Increment repack attempt counter
                        floatingItemRepackAttempts.set(mat.id, currentAttempts + 1);

                        // Add back to current material quantity so they can be repacked!
                        mat.quantity += floatingItemCount;

                        // Update global stats
                        totalItems -= floatingItemCount;
                        unpackedItems += floatingItemCount;

                        load.items = validItems;
                        load.itemCount = validItems.reduce(
                            (sum, item) => sum + (item.itemCount || 0), 0
                        );

                        // Recalculate utilization
                        const loadVol = validItems.reduce(
                            (sum, item) => sum + item.dimensions.length * item.dimensions.width * item.dimensions.height,
                            0
                        );
                        const containerVol = container.dimensions.length * container.dimensions.width * container.dimensions.height;
                        load.utilization = (loadVol / containerVol) * 100;
                    }
                }

                // --- STRATEGY 2: NEW CONTAINER (Fallback) ---

                if (mat.quantity > 0) {
                    // FIX: Clone box to prevent mutation bleed
                    const boxToPack = deepClone(mat.box);
                    const res = packMaterial(
                        boxToPack, container, mat.pallet, mat.quantity, mat.layerConfig, mat.id,
                        0, null, margins, 0
                    );
                    loads = [...loads, ...res.loads];
                    totalItems += res.totalItems;
                    unpackedItems += res.unpackedItems;
                    totalActualUsedVolume += (res.actualUsedVolume || 0);
                    errors = [...errors, ...res.errors];
                    if (i === 0) packedBoxDimensions = res.packedBoxDimensions;
                    // Update remaining quantity for post-processing
                    mat.quantity = res.unpackedItems;
                }
            } else {
                // FIX: Clone box to prevent mutation bleed
                const boxToPack = deepClone(mat.box);
                const res = packMaterial(
                    boxToPack, container, mat.pallet, mat.quantity, mat.layerConfig, mat.id,
                    0, null, margins, 0
                );
                loads = [...loads, ...res.loads];
                totalItems += res.totalItems;
                unpackedItems += res.unpackedItems;
                totalActualUsedVolume += (res.actualUsedVolume || 0);
                errors = [...errors, ...res.errors];
                if (i === 0) packedBoxDimensions = res.packedBoxDimensions;
                // Update remaining quantity for post-processing
                mat.quantity = res.unpackedItems;
            }
        }





        loads.forEach((l, i) => l.id = i + 1);

        return {
            totalItems,
            totalContainers: loads.length,
            loads,
            containerDimensions: container.dimensions,
            unpackedItems,
            packedBoxDimensions,
            errors,
            actualUsedVolume: totalActualUsedVolume
        };
    };

    const baseResult = runSequence(activeMaterials);

    // Apply Pipeline to General Path Results
    let finalLoads = baseResult.loads;
    if ((enableTopUp || enableFullMix) && activeMaterials.length > 0) {
        const primaryMat = activeMaterials[0];
        // FIX: Restore original quantity for pipeline context
        // (runSequence consumes quantity down to 'unpacked', so we must restore it)
        const pipelineMat = { ...primaryMat, quantity: initialQuantities.get(primaryMat.id)! };

        const pipelineResult = runPostProcessingPipeline(
            baseResult.loads,
            pipelineMat, // Use primary material context with restored quantity
            container,
            margins,
            enableTopUp,
            enableFullMix
        );

        finalLoads = pipelineResult.loads;

        // Phase 7: Persist Pipeline Stats (Combined Mode) - Robust Re-summation
        // This ensures the stats purely reflect what is in the final containers
        const finalTotalItems = finalLoads.reduce((s, l) => s + l.itemCount, 0);
        const finalVolume = finalLoads.reduce((s, l) => s + l.items.reduce((v, i) => v + i.dimensions.length * i.dimensions.width * i.dimensions.height, 0), 0);

        // Calculate unpacked based on the delta from base result
        // baseResult.totalItems was the count before pipeline
        // The difference must have come from unpacked items
        const itemsAddedByPipeline = finalTotalItems - baseResult.totalItems;
        const finalUnpacked = Math.max(0, baseResult.unpackedItems - itemsAddedByPipeline);

        baseResult.totalItems = finalTotalItems;
        baseResult.actualUsedVolume = finalVolume;
        baseResult.unpackedItems = finalUnpacked;
    }

    const result = calculateStats({
        ...baseResult,
        loads: finalLoads,
        totalContainers: finalLoads.length
    });

    debugLogger.log('PACKING', 'Calculation complete', {
        totalItems: result.totalItems,
        totalContainers: result.totalContainers,
        errors: result.errors
    });

    return result;
};
